version: '3.4'

services:
  golfgearui: 
    image: golfgearui:latest
    depends_on:
      - golfgear
    ports:
      - "3000:3000"
    networks:
     - golfnet

  golfgear:
    image: golfgear:latest
    depends_on:
      - ravendb
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks: 
      - golfnet
  
  ravendb:
    image: ravendb/ravendb
    ports:
      - "8081:8080"
    environment:
      - RAVEN_ARGS='--Setup.Mode=None'
      - RAVEN_Security_UnsecuredAccessAllowed='PrivateNetwork'
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_PublicServerUrl=http://ravendb:8080
    volumes:
      - golfgear_ravenConfig:/opt/RavenDB/config
      - golfgear_ravenData:/opt/RavenDB/Server/RavenData
    deploy:
      placement:
        constraints: [node.role == manager]
    networks: 
      - golfnet

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - golfnet

networks: 
  golfnet:

volumes:
  golfgear_ravenConfig:
    external: true
  golfgear_ravenData:
    external: true
