version: '3.4'

services:
  # golfgear:
  #   image: modermatt/golfgear:v1
  #   deploy:
  #     replicas: 5
  #     resources:
  #       limits:
  #         cpus: "0.1"
  #         memory: 50M
  #     restart_policy:
  #       condition: on-failure
  #   ports:
  #     - "4000:80"
  #   networks: 
  #     - golfnet
  ravenDb:
    image: ravendb/ravendb
    ports:
      - "8000:8080"
    environment:
      - RAVEN_ARGS='--Setup.Mode=None'
      - RAVEN_Security_UnsecuredAccessAllowed='PrivateNetwork'
    deploy:
      placement:
        constraints: [node.role == manager]
    networks: 
      - golfnet

  # visualizer:
  #   image: dockersamples/visualizer:stable
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   deploy:
  #     placement:
  #       constraints: [node.role == manager]

networks: 
  golfnet:
